apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/airflow-helm/charts.git  # Airflow Helm chart repository
    targetRevision: main
    path: charts/airflow  # The path where the Helm chart is located in the repo
    helm:
      values: |
        airflow:
          executor: "KubernetesExecutor"

        config:
          AIRFLOW__CORE__LOAD_EXAMPLES: "False"
          AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

        flower:
          enabled: false

        redis:
          enabled: false

        postgresql:
          enabled: false

        workers:
          enabled: false
        
        pgbouncer:
          enabled: false

        dags:
          persistence:
            enabled: true

        web:
          defaultUser:
            enabled: true
            username: "admin"
            password: "admin"

        externalDatabase:
          type: postgres
          host: postgresql-ha-postgresql
          port: 5432
          database: postgres
          user: postgres
          passwordSecret: "postgresql-ha-postgresql"
          passwordSecretKey: "password"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true