apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/airflow-helm/charts.git  # Répertoire contenant les charts Helm d'Airflow
    targetRevision: main
    path: charts/airflow
    helm:
      valueFiles:
        - values.yaml  # Fichier de valeurs Helm pour Airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true