airflow:
  executor: "KubernetesExecutor"
  postgresql:
    enabled: false
  externalDatabase:
    ## the type of external database
    ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/database/external-database.md
    type: postgres
    host: a-postgresql-ha-postgresql.dev.svc.cluster.local
    port: 5432
    database: airflow
    user: postgres
    password: fR9QIVp0pA