executor: "KubernetesExecutor"

config:
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

flower:
  enabled: true

redis:
  enabled: true

postgresql:
  enabled: false

dags:
  persistence:
    enabled: true
    replicas: 1
    resources: {}
    capacity: 1000
  flower:
  ## if the airflow flower UI should be deployed
    enabled: false
  reids:
    enabled: false
  dags:
  ## the airflow dags folder
    path: /opt/airflow/dags

web:
  defaultUser:
    enabled: true
    username: "admin"
    password: "admin"



externalDatabase:
  type: postgres
  host: postgresql-ha-postgresql
  port: 5432
  database: postgres
  user: postgres
  passwordSecret: "password"
  passwordSecretKey: "postgresql-ha-postgresql"
