apiVersion: v2
name: infrastructure
description: A Helm chart for Kubernetes

type: application

version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql-ha
    version: 14.2.33
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
